version: 2

sources:
  - name: coffee_shop
    project: analytics-engineers-club
    tables:
      - name: customers
      - name: orders
      - name: order_items
      - name: products
      - name: product_prices

  - name: web_tracking
    project: analytics-engineers-club
    tables:
      - name: pageviews
      