version: 2

models:
  - name: customers
    description: Cleaned up data for our customers
    columns:
      - name: customer_id
        description: Primary key of the model
        tests:
          - unique
          - not_null

  - name: monthly_new_customers
    description: New customers by month
    columns:
      - name: date_snapshot 
        description: the monthly date of new customers
        tests:
          - not_null

      - name: customer_id
        description: unique id of the customer
        tests:
          - not_null
          - unique

      - name: name
        description: name of the customer
        tests:
          - not_null

      - name: email
        description: email address of the customer
        tests:
          - not_null

      - name: min_order_at
        description: earliest order of the customer
        tests:
          - not_null
          
      - name: num_of_orders
        description: number of orders of the customer
        tests:
          - not_null

  - name: page_views_visitor_stitch
    description: '{{ doc("db_test") }}'

  - name: page_views_sessions

  - name: weekly_customer_orders
          
  - name: fact_order_items
    description: Individual orderitems w/ relevant keys
    columns:
      - name: id
        description: Primary key of the model
        tests:
          - not_null
      - name: order_id
        description: Id of the relevant order
        tests:
          - not_null
      - name: product_id
        description: Id of the product
        tests:
          - not_null
      - name: created_at
        description: UTC time of creation
        tests:
          - not_null
      - name: customer_id
        description: Id of the customer
        tests:
          - not_null
      - name: product_price_id
        description: Id of the price of the product
        tests:
          - not_null
      - name: price
        description: Price of the product at the time of sale
        tests:
          - not_null